# Generated by Django 4.2 on 2026-03-07 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_leave_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('A', 'Working'), ('I', 'Resigned'), ('R', 'Retired')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='DailySalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_salary_slip', to='gate.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_salary_slips', to='gate.employee')),
            ],
            options={
                'verbose_name_plural': 'Daily Salary Slips',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysalaryslip',
            index=models.Index(fields=['employee', 'date'], name='gate_dailys_employe_a66201_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysalaryslip',
            index=models.Index(fields=['date'], name='gate_dailys_date_ffe910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysalaryslip',
            unique_together={('employee', 'date')},
        ),
    ]
